version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: footwork-postgres
    environment:
      POSTGRES_DB: footwork_db
      POSTGRES_USER: footwork_user
      POSTGRES_PASSWORD: footwork_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: